import * as u from "@/helpers/utilities";
import { type GeneralIconVariant } from "@/entities/icons";

export type Feature = {
  id: (typeof ARRAY)[number];
  label: string;
  description: string;
  icon: GeneralIconVariant;
};

const ARRAY = [
  "browser-non-google-engine",
  "browser-native-add-blocking",
  "browser-built-in-vpn",
  "browser-ai-helper",
  "browser-ecosystem-support",
  "browser-good-user-support",
  "email-alias-creation",
  "email-easy-unsubscribe",
  "email-schedule-send",
  "email-automatic-categorization",
  "email-ecosystem-support",
  "email-good-user-support",
  "search-independent-index",
  "search-no-personal-identifiers",
  "search-ad-free-tier",
  "search-ai-summaries",
  "search-ecosystem-support",
  "search-good-user-support",
  "music-generous-artist-royalties",
  "music-purchaseable-content",
  "music-high-res-streaming",
  "music-ai-content-flagged",
  "music-ecosystem-support",
  "music-good-user-support",
  "audiobooks-drm-free",
  "audiobooks-subscription",
  "audiobooks-rentals",
  "audiobooks-ecosystem-support",
  "audiobooks-good-support",
  "office-online-service",
  "office-mobile-app",
  "office-own-software",
  "office-ai-assistance",
  "office-good-support",
  "photos-live-images",
  "photos-facial-recognition",
  "photos-file-storage-support",
  "photos-good-support",
] as const;

const LABELS: Record<Feature["id"], string> = {
  "browser-non-google-engine": "",
  "browser-native-add-blocking": "",
  "browser-built-in-vpn": "",
  "browser-ai-helper": "",
  "browser-ecosystem-support": "",
  "browser-good-user-support": "",
  "email-alias-creation": "",
  "email-easy-unsubscribe": "",
  "email-schedule-send": "",
  "email-automatic-categorization": "",
  "email-ecosystem-support": "",
  "email-good-user-support": "",
  "search-independent-index": "",
  "search-no-personal-identifiers": "",
  "search-ad-free-tier": "",
  "search-ai-summaries": "",
  "search-ecosystem-support": "",
  "search-good-user-support": "",
  "music-generous-artist-royalties": "",
  "music-purchaseable-content": "",
  "music-high-res-streaming": "",
  "music-ai-content-flagged": "",
  "music-ecosystem-support": "",
  "music-good-user-support": "",
  "audiobooks-drm-free": "",
  "audiobooks-subscription": "",
  "audiobooks-rentals": "",
  "audiobooks-ecosystem-support": "",
  "audiobooks-good-support": "",
  "office-online-service": "",
  "office-mobile-app": "",
  "office-own-software": "",
  "office-ai-assistance": "",
  "office-good-support": "",
  "photos-live-images": "",
  "photos-facial-recognition": "",
  "photos-file-storage-support": "",
  "photos-good-support": "",
} as const;

const DESCRIPTIONS: Record<Feature["id"], string> = {
  "browser-non-google-engine": "",
  "browser-native-add-blocking": "",
  "browser-built-in-vpn": "",
  "browser-ai-helper": "",
  "browser-ecosystem-support": "",
  "browser-good-user-support": "",
  "email-alias-creation": "",
  "email-easy-unsubscribe": "",
  "email-schedule-send": "",
  "email-automatic-categorization": "",
  "email-ecosystem-support": "",
  "email-good-user-support": "",
  "search-independent-index": "",
  "search-no-personal-identifiers": "",
  "search-ad-free-tier": "",
  "search-ai-summaries": "",
  "search-ecosystem-support": "",
  "search-good-user-support": "",
  "music-generous-artist-royalties": "",
  "music-purchaseable-content": "",
  "music-high-res-streaming": "",
  "music-ai-content-flagged": "",
  "music-ecosystem-support": "",
  "music-good-user-support": "",
  "audiobooks-drm-free": "",
  "audiobooks-subscription": "",
  "audiobooks-rentals": "",
  "audiobooks-ecosystem-support": "",
  "audiobooks-good-support": "",
  "office-online-service": "",
  "office-mobile-app": "",
  "office-own-software": "",
  "office-ai-assistance": "",
  "office-good-support": "",
  "photos-live-images": "",
  "photos-facial-recognition": "",
  "photos-file-storage-support": "",
  "photos-good-support": "",
};

const ICONS: Record<Feature["id"], GeneralIconVariant> = {
  "browser-non-google-engine": "star",
  "browser-native-add-blocking": "star",
  "browser-built-in-vpn": "star",
  "browser-ai-helper": "star",
  "browser-ecosystem-support": "star",
  "browser-good-user-support": "star",
  "email-alias-creation": "star",
  "email-easy-unsubscribe": "star",
  "email-schedule-send": "star",
  "email-automatic-categorization": "star",
  "email-ecosystem-support": "star",
  "email-good-user-support": "star",
  "search-independent-index": "star",
  "search-no-personal-identifiers": "star",
  "search-ad-free-tier": "star",
  "search-ai-summaries": "star",
  "search-ecosystem-support": "star",
  "search-good-user-support": "star",
  "music-generous-artist-royalties": "star",
  "music-purchaseable-content": "star",
  "music-high-res-streaming": "star",
  "music-ai-content-flagged": "star",
  "music-ecosystem-support": "star",
  "music-good-user-support": "star",
  "audiobooks-drm-free": "star",
  "audiobooks-subscription": "star",
  "audiobooks-rentals": "star",
  "audiobooks-ecosystem-support": "star",
  "audiobooks-good-support": "star",
  "office-online-service": "star",
  "office-mobile-app": "star",
  "office-own-software": "star",
  "office-ai-assistance": "star",
  "office-good-support": "star",
  "photos-live-images": "star",
  "photos-facial-recognition": "star",
  "photos-file-storage-support": "star",
  "photos-good-support": "star",
};

export const FEATURE_VARIANTS = u.fromArray(
  ARRAY.map(
    (id): Feature => ({
      id,
      label: LABELS[id],
      description: DESCRIPTIONS[id],
      icon: ICONS[id],
    })
  )
);
