import * as u from "@/helpers/utilities";
import { type GeneralIconVariant, type IconVariant } from "@/entities/icons";

export type Feature = {
  id: (typeof ARRAY)[number];
  label: string;
  description: string;
  icon: IconVariant;
};

const ARRAY = [
  "browser-non-google-engine",
  "browser-native-add-blocking",
  "browser-built-in-vpn",
  "browser-ai-helper",
  "browser-ecosystem-support",
  "browser-good-user-support",
  "browser-good-user-support-partial",
  "browser-zero-telemetry",
  "email-alias-creation",
  "email-easy-unsubscribe",
  "email-schedule-send",
  "email-automatic-categorization",
  "email-ecosystem-support",
  "email-good-user-support",
  "email-good-user-support-partial",
  "email-email-address",
  "search-independent-index",
  "search-no-personal-identifiers",
  "search-ad-free-tier",
  "search-ai-summaries",
  "search-ecosystem-support",
  "search-good-user-support",
  "search-good-user-support-partial",
  "music-generous-artist-royalties",
  "music-purchaseable-content",
  "music-high-res-streaming",
  "music-ai-content-flagged",
  "music-ecosystem-support",
  "music-good-user-support",
  "music-good-user-support-partial",
  "audiobooks-drm-free",
  "audiobooks-subscription",
  "audiobooks-rentals",
  "audiobooks-ecosystem-support",
  "audiobooks-good-support",
  "audiobooks-good-support-partial",
  "office-online-service",
  "office-mobile-app",
  "office-own-software",
  "office-ai-assistance",
  "office-good-support",
  "office-good-support-partial",
  "office-ecosystem-support",
  "photos-live-images",
  "photos-facial-recognition",
  "photos-file-storage-support",
  "photos-good-support",
  "photos-photo-editing",
  "photos-memories",
  "storage-online-office",
  "storage-zero-knowledge",
  "storage-image-search",
  "storage-ecosystem-support",
  "storage-good-support",
] as const;

const LABELS: Record<Feature["id"], string> = {
  "browser-non-google-engine": "Non-Google Engine",
  "browser-native-add-blocking": "Built-in Ad Blocker",
  "browser-built-in-vpn": "Built-in VPN",
  "browser-ai-helper": "AI Assistant",
  "browser-ecosystem-support": "Larger ecosystem",
  "browser-good-user-support": "Good User Support",
  "browser-good-user-support-partial": "Partial User Support",
  "browser-zero-telemetry": "Zero Telemetry",
  "email-alias-creation": "Alias Creation",
  "email-easy-unsubscribe": "Easy Email Unsubscribe",
  "email-schedule-send": "Schedule Send",
  "email-automatic-categorization": "Auto Email Categorization",
  "email-ecosystem-support": "Larger Ecosystem",
  "email-good-user-support": "Good User Support",
  "email-good-user-support-partial": "Partial User Support",
  "email-email-address": "Email Address Included",
  "search-independent-index": "Independent Index",
  "search-no-personal-identifiers": "No Personal Tracking",
  "search-ad-free-tier": "Ad-Free Tier",
  "search-ai-summaries": "AI Summaries",
  "search-ecosystem-support": "Larger Ecosystem",
  "search-good-user-support": "Good User Support",
  "search-good-user-support-partial": "Partial User Support",
  "music-generous-artist-royalties": "High Artist Royalties",
  "music-purchaseable-content": "Purchaseable Music",
  "music-high-res-streaming": "High-Res Streaming",
  "music-ai-content-flagged": "Anti-AI Policies",
  "music-ecosystem-support": "Ecosystem Support",
  "music-good-user-support": "Good User Support",
  "music-good-user-support-partial": "Partial User Support",
  "audiobooks-drm-free": "DRM-Free Downloads",
  "audiobooks-subscription": "Subscription Model",
  "audiobooks-rentals": "Rental Options",
  "audiobooks-ecosystem-support": "Larger Ecosystem",
  "audiobooks-good-support": "Good User Support",
  "audiobooks-good-support-partial": "Partial User Support",
  "office-online-service": "Online Service",
  "office-mobile-app": "Mobile App",
  "office-own-software": "Their Own Software",
  "office-ai-assistance": "AI Office Assistant",
  "office-good-support": "Good User Support",
  "office-good-support-partial": "Partial User Support",
  "office-ecosystem-support": "Larger Ecosystem",
  "photos-live-images": "Live Images",
  "photos-facial-recognition": "Facial Recognition",
  "photos-file-storage-support": "Larger Ecosystem",
  "photos-good-support": "Good User Support",
  "photos-photo-editing": "Photo Editing",
  "photos-memories": "Memories",
  "storage-online-office": "Online office",
  "storage-zero-knowledge": "Zero Knowledge Encryption",
  "storage-image-search": "Image Search Capabilities",
  "storage-ecosystem-support": "Larger ecosystem",
  "storage-good-support": "Good User Support",
} as const;

const DESCRIPTIONS: Record<Feature["id"], string> = {
  "browser-non-google-engine":
    "Isn't impacted by Google's decisions e.g. dropping support for ad-blocking extensions",
  "browser-native-add-blocking":
    "Default installation comes with an ad-blocker built-in or a preconfigured ad-blocking extension",
  "browser-built-in-vpn": "Integrated VPN service for enhanced privacy",
  "browser-ai-helper":
    "Integrated AI helper that integrates into browsing experience",
  "browser-ecosystem-support":
    "Offers a VPN as an additional tool within their ecosystem",
  "browser-good-user-support":
    "Forum, community app or email where support within 24 hours is available",
  "browser-good-user-support-partial":
    "Forum, community app or email where support within 24 hours is available",
  "browser-zero-telemetry": "Limited or no telemetry (tracking or analytical data) is reported back to the company",
  "email-alias-creation": "Create email aliases to protect your main address",
  "email-easy-unsubscribe": "Quick unsubscribe action prompt for unwanted newsletters",
  "email-automatic-categorization": "Automatic classification of social media messages and promotional communication into specific folders",
  "email-schedule-send": "Emails can be sent at a specific time",
  "email-ecosystem-support": "Offers storage, docs or other productivity tools within their ecosystem",
  "email-good-user-support": "Phone or live chat where support is immediately available",
  "email-good-user-support-partial": "Forum, community app or email where support within 24 hours is available",
  "email-email-address": "Email Address Included",
  "search-independent-index":
    "Provides their own search results alongside of Google or Bing",
  "search-no-personal-identifiers":
    "Does not collect any Personal Identification Information (PII)",
  "search-ad-free-tier": "Has an avenue to search without ads or sponsored results",
  "search-ai-summaries": "Optional AI summary provided for certain queries",
  "search-ecosystem-support": "Offers a browser, VPN or other tools within their ecosystem",
  "search-good-user-support": "Phone or live chat where support is immediately available",
  "search-good-user-support-partial":
    "Forum, community app or email where support within 24 hours is available",
  "music-generous-artist-royalties": "Estimated artist payout of more than 1 cent per stream or purchase",
  "music-purchaseable-content":
    "They allow you to own your songs and offer 75%+ revenue to artists",
  "music-high-res-streaming": "Offers streaming of tracks at a quality of 24-bit/192kHz",
  "music-ai-content-flagged": "Provides and enforces policies that actively flag or fight against AI content",
  "music-ecosystem-support": "Works with various devices and platforms",
  "music-good-user-support": "Phone or live chat where support is immediately available",
  "music-good-user-support-partial":
    "Forum, community app or email where support within 24 hours is available",
  "audiobooks-drm-free":
    "Allows you to own your media and play it on any device",
  "audiobooks-subscription": "Offers subscriptions for unlimited streaming or monthly credits",
  "audiobooks-rentals": "Rent audiobooks for a limited time at lower cost",
  "audiobooks-ecosystem-support": "Books, e-books or podcasts are provided",
  "audiobooks-good-support": "Phone or live chat where support is immediately available",
  "audiobooks-good-support-partial":
    "Forum, community app or email where support within 24 hours is available",
  "office-online-service": "Web-based access without software installation",
  "office-mobile-app": "Full-featured mobile applications available",
  "office-own-software": "Purchase and own the software permanently",
  "office-ai-assistance": "Integrated AI helper that works alongside office tools",
  "office-good-support": "Phone or live chat where support is immediately available",
  "office-good-support-partial": "Limited support or documentation",
  "office-ecosystem-support": "Offers Meetings, Storage or other productivity tools within their ecosystem",
  "photos-live-images": "Support for animated photos and live image formats",
  "photos-facial-recognition": "Automatic face detection and tagging features",
  "photos-file-storage-support": "Offers a dedicated file storage tool within their ecoystem", 
  "photos-good-support": "Forum, community app or email where support within 24 hours is available",
  "photos-photo-editing": "Built-in photo editing and enhancement tools",
  "photos-memories": "Automated collections of photos based on time and location",
  "storage-online-office": "Integrated with a full-suite online office service",
  "storage-zero-knowledge": "Default settings provide zero-knowledge end-to-end encryption for data stored",
  "storage-image-search": "Image search capabilities matching on objects and people",
  "storage-ecosystem-support": "Offers meetings, chat or productivity tools within their ecosystem",
  "storage-good-support": "Phone or live chat where support is immediately available",
};

const ICONS: Record<Feature["id"], IconVariant> = {
  "browser-non-google-engine": "cpu",
  "browser-native-add-blocking": "shield-check",
  "browser-built-in-vpn": "shield",
  "browser-ai-helper": "brain",
  "browser-ecosystem-support": "link",
  "browser-good-user-support": "user-check",
  "browser-good-user-support-partial": "user-check",
  "browser-zero-telemetry": "eye-off",
  "email-alias-creation": "tag",
  "email-easy-unsubscribe": "check-circle",
  "email-schedule-send": "calendar",
  "email-automatic-categorization": "filter",
  "email-ecosystem-support": "link",
  "email-good-user-support": "user-check",
  "email-good-user-support-partial": "user-check",
  "email-email-address": "info",
  "search-independent-index": "database",
  "search-no-personal-identifiers": "eye-off",
  "search-ad-free-tier": "award",
  "search-ai-summaries": "brain",
  "search-ecosystem-support": "link",
  "search-good-user-support": "user-check",
  "search-good-user-support-partial": "user-check",
  "music-generous-artist-royalties": "trending-up",
  "music-purchaseable-content": "shopping-cart",
  "music-high-res-streaming": "headphones",
  "music-ai-content-flagged": "info",
  "music-ecosystem-support": "link",
  "music-good-user-support": "user-check",
  "music-good-user-support-partial": "user-check",
  "audiobooks-drm-free": "unlock",
  "audiobooks-subscription": "play-circle",
  "audiobooks-rentals": "clock",
  "audiobooks-ecosystem-support": "link",
  "audiobooks-good-support": "user-check",
  "audiobooks-good-support-partial": "user-check",
  "office-online-service": "globe",
  "office-mobile-app": "smartphone",
  "office-own-software": "package",
  "office-ai-assistance": "brain",
  "office-good-support": "user-check",
  "office-good-support-partial": "user-check",
  "office-ecosystem-support": "link",
  "photos-live-images": "camera",
  "photos-facial-recognition": "scan-face",
  "photos-file-storage-support": "cloud-upload",
  "photos-good-support": "user-check",
  "photos-photo-editing": "filter",
  "photos-memories": "calendar",
  "storage-online-office": "notebook-text",
  "storage-zero-knowledge": "lock",
  "storage-image-search": "camera",
  "storage-ecosystem-support": "link",
  "storage-good-support": "user-check",
};

export const FEATURE_VARIANTS = u.fromArray(
  ARRAY.map(
    (id): Feature => ({
      id,
      label: LABELS[id],
      description: DESCRIPTIONS[id],
      icon: ICONS[id],
    })
  )
);
