import { type Props as IconProps } from "@/components/Icon";
import { type Item } from "@/entities/Software";

export const ICON_MAP: Record<Item["features"][number], IconProps["variant"]> =
  {
    "browser-non-google-engine": "check",
    "browser-native-add-blocking": "check",
    "browser-built-in-vpn": "check",
    "browser-ai-helper": "check",
    "browser-ecosystem-support": "check",
    "browser-good-user-support": "check",
    "email-alias-creation": "check",
    "email-easy-unsubscribe": "check",
    "email-schedule-send": "check",
    "email-automatic-categorization": "check",
    "email-ecosystem-support": "check",
    "email-good-user-support": "check",
    "search-independent-index": "check",
    "search-no-personal-identifiers": "check",
    "search-ad-free-tier": "check",
    "search-ai-summaries": "check",
    "search-ecosystem-support": "check",
    "search-good-user-support": "check",
    "music-generous-artist-royalties": "check",
    "music-purchaseable-content": "check",
    "music-high-res-streaming": "check",
    "music-ai-content-flagged": "check",
    "music-ecosystem-support": "check",
    "music-good-user-support": "check",
    "audiobooks-drm-free": "check",
    "audiobooks-subscription": "check",
    "audiobooks-rentals": "check",
    "audiobooks-ecosystem-support": "check",
    "audiobooks-good-support": "check",
    "office-online-service": "check",
    "office-mobile-app": "check",
    "office-own-software": "check",
    "office-ai-assistance": "check",
    "office-good-support": "check",
    "photos-live-images": "check",
    "photos-facial-recognition": "check",
    "photos-file-storage-support": "check",
    "photos-good-support": "check",
  };
