# media_folder: "src/public/images/content" 
# public_folder: "/images/content" 
backend:
  name: github
  repo: purchase-with-purpose/website
collections:
  - name: "products" 
    label: "Products" 
    folder: "src/content/products" 
    create: true 
    fields: 
      - { label: "Product Name", name: "label", widget: "string" }
