import { type Origin } from "@/entities/software";
import {
  Cpu,
  ShieldCheck,
  Shield,
  Brain,
  Link,
  UserCheck,
  Tag,
  CheckCircle,
  Calendar,
  Filter,
  Database,
  EyeOff,
  Award,
  Info,
  TrendingUp,
  ShoppingCart,
  Headphones,
  Unlock,
  PlayCircle,
  Clock,
  Globe,
  Smartphone,
  Package,
  Camera,
  ScanFace,
  CloudUpload,
  Leaf,
  HardDrive,
  ChartPie,
  NotebookText,
  ChevronDown,
} from "lucide-react";

export const LUCIDE_ICONS = {
  cpu: Cpu,
  "shield-check": ShieldCheck,
  shield: Shield,
  brain: Brain,
  link: Link,
  "user-check": UserCheck,
  tag: Tag,
  "check-circle": CheckCircle,
  calendar: Calendar,
  filter: Filter,
  database: Database,
  "eye-off": EyeOff,
  award: Award,
  info: Info,
  "trending-up": TrendingUp,
  "shopping-cart": ShoppingCart,
  headphones: Headphones,
  unlock: Unlock,
  "play-circle": PlayCircle,
  clock: Clock,
  globe: Globe,
  smartphone: Smartphone,
  package: Package,
  camera: Camera,
  "scan-face": ScanFace,
  "cloud-upload": CloudUpload,
  leaf: Leaf,
  harddrive: HardDrive,
  "chart-pie": ChartPie,
  "notebook-text": NotebookText,
  "chevron-down": ChevronDown,
} as const;

export const GENERAL_ICON_VARIANTS = [
  "company",
  "person",
  "check",
  "warning",
  "cross",
  "none",
  "unknown",
  "slice",
  "tag",
  "shapes",
  "database",
  "combine",
  "face",
  "lock",
  "bookmark",
  "country",
  "trophy",
  "smartphone",
  "eye",
  "desktop",
  "globe",
  "notes",
  "star",
  "level-one",
  "level-two",
  "level-three",
  "info",
  "box",
  "audiobook",
  "image",
  "search",
  "speaker",
  "writing",
] as const;

export type LucideIconVariant = keyof typeof LUCIDE_ICONS;
export type GeneralIconVariant = (typeof GENERAL_ICON_VARIANTS)[number];
export type FlagIconVariant = `flag-${Lowercase<Origin["id"]>}`;

export type IconVariant =
  | GeneralIconVariant
  | FlagIconVariant
  | LucideIconVariant;
